name: default

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug git history
        run: git log --oneline

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: git fetch origin main

      - run: npm install

      - run: npx nx affected --target=semantic-release --base=${{ github.event.before }} --head=${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NX_BRANCH: ${{ github.base_ref }}
          NX_BASE: ${{ github.event.pull_request.base.sha }}
          NX_HEAD: ${{ github.event.pull_request.head.sha }}
