name: default

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: git fetch origin main
      
      - run: npm install
      
      - run: npm ci
      
      - run: npx nx affected --target=semantic-release --base=remotes/origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
